[package]
name = "rustWindowsTcpWebserver"
version = "0.1.0"
edition = "2021"


[dependencies]
winapi = { version = "0.3.9", features = ["inaddr", "ws2def", "winsock2"] }
serde_json = "1.0.134"
serde = { version = "1.0.217", features = ["derive"] }
lazy_static = "1.5.0"
